# Change these first
owner: ONEcampaign # Your GitHub username
repo: project_upptime # Your Github repository name

# Add your sites here
sites:
  - name: Actionkit
    url: https://act.one.org
  - name: Africa Mobile Site
    url: https://m.one.org/us
  - name: Bridge Messaging Platform
    url: api.messaging.dev.one.org/prod/gqlgw/countries/fuzzySearch?search=test
  - name: Bynder
    url: https://assets.one.org
  - name: Dashboard
    url: https://dashboard.one.org
  - name: Intranet
    url: https://intranet.one.org
  - name: ONE Against Poverty UK
    url: https://www.oneagainstpoverty.org.uk
  - name: ONE Global Canada
    url: https://www.oneglobalcanada.com
  - name: ONE
    url: https://www.one.org
  - name: ONE Africa
    url: https://www.one.org/africa
  - name: ONE International
    url: https://www.one.org/international
  - name: ONE Activists
    url: https://activists.one.org/
  - name: Accountability Music Awards
    url: https://www.accountabilitymusicawards.org
  - name: ONE US
    url: https://www.one.org/us
  - name: Rapidpro
    url: https://one.wafl.chat
  - name: Scorecards
    url: https://scorecards.one.org
  - name: Staging
    url: https://staging.one.org/international


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.one.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://www.one.org/wp-content/themes/one_2014/dist/images/ONE-logo-black.png
  name: ONE Status
  introTitle: "ONE.org status"
  introMessage: This is the status page for ONE services and websites
  navbar:
    - title: Status
      href: /
    - title: ONE.org
      href: https://one.org/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
